---
title: "educ-constraint"
author: "Marissa Block"
date: "2/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(treemapify)
library(RColorBrewer)
library(haven)
library(readxl)
library(sf)
library(extrafont)
library(ggrepel)
library(ggridges)
library(waffle)

# Load Data

```


# Education as a Binding Constraint


## Benchmarking
```{r}

## Quantity of Schooling
# Filter to 2010 years of schooling
yrs <- edstats %>%
  filter(year==2010) %>%
  select(country, bar.schl.15up)

wdi %>%
  filter(year==2016) %>%
  left_join(yrs) %>%
  select(country, bar.schl.15up, ny.gdp.pcap.kd, cntry.code) %>%
  ggplot(aes(x = (ny.gdp.pcap.kd), y = bar.schl.15up)) +
  geom_point() +
  #geom_label(aes(label = cntry.code)) +
  geom_smooth()

## Quality of Schooling
wdi %>%
  select(country, cntry.code, year, ny.gdp.pcap.kd) %>%
  filter(year==2017) %>%
  left_join(edstats) %>%
  select(country, ny.gdp.pcap.kd, cntry.code, hd.hci.hlos) %>%
  ggplot(aes(x = log(ny.gdp.pcap.kd), y = hd.hci.hlos)) +
  geom_point() +
  geom_label(aes(label=cntry.code)) +
  geom_smooth()
```

## Test 1: Returns to Schooling

```{r}
# First, filter to get overall returns for most recent year in which data is available
returns.ovr <- returns %>%
  group_by(country) %>%
  filter(!is.na(overall)) %>%
  filter(year == max(year)) %>%
  rename(year.return = "year", source.ovr = "source") %>%
  select(country, year.return, overall, source.ovr) %>%
  mutate(globalAvgOverall = 9)

returns.prim <- returns %>%
  group_by(country) %>%
  filter(!is.na(primary)) %>%
  filter(year == max(year)) %>%
  rename(year.return = "year", source.prim = "source") %>%
  select(country, year.return, primary, source.prim)

returns.sec <- returns %>%
  group_by(country) %>%
  filter(!is.na(secondary)) %>%
  filter(year == max(year)) %>%
  rename(year.return = "year", source.sec = "source") %>%
  select(country, year.return, secondary, source.sec)

returns.high <- returns %>%
  group_by(country) %>%
  filter(!is.na(higher)) %>%
  filter(year == max(year)) %>%
  rename(year.return = "year", source.high = "source") %>%
  select(country, year.return, higher, source.high)

returns.male <- returns %>%
  group_by(country) %>%
  filter(!is.na(male)) %>%
  filter(year == max(year)) %>%
  rename(year.return = "year", source.male = "source") %>%
  select(country, year.return, male, source.male)

returns.female <- returns %>%
  group_by(country) %>%
  filter(!is.na(female)) %>%
  filter(year == max(year)) %>%
  rename(year.return = "year", source.female = "source") %>%
  select(country, year.return, female, source.female)




  
merge <- returns.ovr %>%
  full_join(returns.prim) %>%
  full_join(returns.sec) %>%
  full_join(returns.high) %>%
  full_join(returns.male) %>%
  full_join(returns.female) %>%
  gather("overall", "primary", "secondary", "higher", "male", "female", "globalAvgOverall", key = "type", value = "value") %>%
  gather("source.ovr", "source.prim", "source.sec", "source.high", "source.male", "source.female", key = "source.type", value = "source") %>%
  rename(year = "year.return") %>%
  arrange(country, year) %>%
  filter(!is.na(value)) %>%
  filter(!is.na(source)) %>%
  select(-source.type) %>%
  unique() %>%
  write_csv(path = "data/clean/returns2.csv")
  
  

returns.ovr %>%
  select(country, overall) %>%
  arrange(overall) %>%
  mutate(country2 = factor(country, levels = .$country)) %>%
  ggplot(aes(country, overall)) +
    geom_segment(aes(x = 0, xend = return, y = country2, yend = country2)) +
    geom_point()
  



```

# Test 2: Changes vs. Changes
```{r}
# Connected Scatterplot: http://steveharoz.com/research/connected_scatterplot/
wdi.time %>%
  group_by(country) %>%
  mutate(secGrowth = (se.sec.enrr - lag(se.sec.enrr))/lag(se.sec.enrr)) %>%
  filter(country=="Chile") %>%
  ggplot(aes(x = ny.gdp.pcap.kd.zg, y = secGrowth, label = year)) +
    geom_point() +
    geom_label(aes(label = year)) +
    geom_segment(aes(xend=c(tail(ny.gdp.pcap.kd.zg, n = -1), NA),
                    yend=c(tail(secGrowth, n = -1), NA)),
                    arrow = arrow(length=unit(0.3, "cm"))) +
    labs(
      x = "GDP per capita Growth",
      y = "Growth in Secondary School Enrollment Rate"
    )
  
```

